name: nbenv
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - python=3.9
  - numba==0.56.4
  - numpy=1.23.5
  - matplotlib
  - pandas
  - tqdm
  - joblib
  - biopython
  - abnumber
  - pdbfixer
  - pdb2pqr
  - openmm
  - openmmforcefields
  - openff-toolkit
  - mdtraj
  - jupyterlab
  - pip
  
